### PR TITLE
add swagger-ui for /api-docs

### LINKED ISSUE #65: Evaluate adding a swagger UI interface
e.g. https://github.com/batdevis/swagger_engine

### PR DESCRIPTION
**Pull request by dazza-codes**
WIP to fix #65 

Extracted some minor commits into PR #68.  Once that is merged, this PR will be easier to review.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
When this is up, it fails to issue correct requests, e.g.
`curl -X GET --header "Accept: application/json" "https://localhost:3000/node/sdr"`

It is missing an `Authorization` header option and it is using `https` for the localhost in development environment.

**Comment by malakai97** [comment]
- `lib/swagger/api_v2.json` and `lib/swagger/swagger.json` these two files appear to be duplicates
- `lib/swagger/swagger.yaml` both of the above are derivative of this file

Swagger claims to be able to handle yaml whenever it asks for json; have you tried supplying only the yaml in this PR?

---

I am concerned that the inclusion of the compiled spec into dpn-server, be it as swagger.json/api_v2.json/swagger.yaml, introduces a second source of truth; and that this will lead to discrepancies between the specification contained within dpn-server and the authoritative specification contained within dpn-rest-spec.  

How will we ensure that dpn-server's swagger specification does not diverge from that of dpn-rest-spec?  

I can think of two alternative strategies, but neither is particularly compelling:
1. Have the dpn-server swagger api directly reference the compiled spec in
   the dpn-rest-spec repo.  It would have to bind to a specific commit or tag.
2. Have the dpn-server pull down the dpn-rest-spec specification as part of
   configuration.  It would still have to bind to a specific commit or tag.

**Comment by dazza-codes** [comment]
1.  I'll test using the `swagger.yaml` file directly.
2. I've considered adding a git submodule for the rest spec when building the dpn_swagger_engine gem or for the dpn-server:lib/swagger/swagger.yaml file, but not tested those options yet.
   - 2.1 Waiting on trying to get automated link to the authoritative swagger spec when the api-v2 spec is merged into master.  Then a git submodule might do the trick (although I'm a bit vague on details for tracking a specific file rather than the entire repo).

**Comment by dazza-codes** [comment]
I've added a git submodule and symlink for the swagger.yaml file.  Now I need to figure out whether to have the dpn-rest-spec project create a swagger.json file or to see if dpn_swagger_engine can work with a swagger.yaml file instead of a JSON file.

**Comment by dazza-codes** [comment]
After reading https://github.com/swagger-api/swagger-ui/issues/595, it's clear that we should have a `dist/swagger.json` file in the dpn-rest-spec:api-v2 project.  When that is available, the symlinks for it in this project can be updated to use it.

Pending work on https://github.com/dpn-admin/dpn-rest-spec/issues/5

**Comment by dazza-codes** [comment]
Updated to use symlinks into `dpn-rest-spec:dist/swagger.*` based on `dpn-rest-spec:dist-swagger-json` branch.  Works OK on my laptop.

See also https://github.com/dpn-admin/dpn-rest-spec/pull/8

**Comment by malakai97** [comment]
merged subordinate pr #68, probably want to rebase this

**Comment by dazza-codes** [comment]
This PR is currently using a branch from https://github.com/dpn-admin/dpn-rest-spec/pull/8

**Comment by dazza-codes** [comment]
After we merged dpn-admin/dpn-rest-spec#8, updated the git submodule to point to the `api-v2` branch files for `dist/swagger.yaml` and `dist/swagger.json`.  When we merge https://github.com/dpn-admin/dpn-rest-spec/pull/4, the git submodule can point to the `master` branch (but that could be done in another PR, unless that merge happens soon).  Consider this open for review/merge now (removed the [WIP] tag from the title).

**Comment by malakai97** [comment]
This is ready to point to dpn-rest-spec master.  Is it ready to merge after that change?

**Pull request merged**
