### PR TITLE
[WIP] Fix message digests migrations

### PR DESCRIPTION
**Pull request by dazza-codes**
This was validated on MySQL, the resulting details are given below.

### CODE REVIEW

**Comment by dazza-codes** [comment]
On MySQL, this migration results in:

``` SQL
CREATE TABLE `message_digests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bag_id` int(11) NOT NULL,
  `fixity_alg_id` int(11) NOT NULL,
  `value` text COLLATE utf8_unicode_ci NOT NULL,
  `node_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_message_digests_on_bag_id_and_fixity_alg_id` (`bag_id`,`fixity_alg_id`),
  KEY `fk_rails_592f5598b9` (`fixity_alg_id`),
  KEY `message_digests_nodes_id_fk` (`node_id`),
  CONSTRAINT `fk_rails_592f5598b9` FOREIGN KEY (`fixity_alg_id`) REFERENCES `fixity_algs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `message_digests_bags_id_fk` FOREIGN KEY (`bag_id`) REFERENCES `bags` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `message_digests_nodes_id_fk` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

The equivalent ruby/rails code is:

``` ruby
  create_table "message_digests", force: :cascade do |t|
    t.integer  "bag_id",        limit: 4,     null: false
    t.integer  "fixity_alg_id", limit: 4,     null: false
    t.text     "value",         limit: 65535, null: false
    t.integer  "node_id",       limit: 4,     null: false
    t.datetime "created_at",                  null: false
  end

  add_index "message_digests", ["bag_id", "fixity_alg_id"], name: "index_message_digests_on_bag_id_and_fixity_alg_id", unique: tru
e, using: :btree
  add_index "message_digests", ["fixity_alg_id"], name: "fk_rails_592f5598b9", using: :btree
  add_index "message_digests", ["node_id"], name: "message_digests_nodes_id_fk", using: :btree
```

**Comment by dazza-codes** [comment]
This migration still fails when deploying to SDR dpn-dev, i.e.

```
== 20160927230135 NodeNotNullInMessageDigest: migrating =======================
-- change_column(:message_digests, :node_id, :integer, {:null=>false})
rake stderr: Unknown ruby interpreter version (do not know how to handle): ~>2.3.0.
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Error on rename of './dpn@002dserver/#sql-7ab_40c03' to './dpn@002dserver/message_digests' (errno: 150): ALTER TABLE `message_digests` CHANGE `node_id` `node_id` int(11) NOT NULL
```

**Comment by eefahy** [comment]
from running `SHOW ENGINE INNODB STATUS`

``` ------------------------
LATEST FOREIGN KEY ERROR
------------------------
161007 13:01:38 Error in foreign key constraint of table dpn@002dserver/message_digests:
there is no index in the table which would contain
the columns as the first columns, or the data types in the
table do not match the ones in the referenced table
or one of the ON ... SET NULL columns is declared NOT NULL. Constraint:
,
  CONSTRAINT "fk_rails_d4e6ffe21c" FOREIGN KEY ("node_id") REFERENCES "nodes" ("id") ON DELETE SET NULL ON UPDATE CASCADE
```

**Comment by dazza-codes** [comment]
When I use a mysqldump of the SDR dpn-dev data on my laptop and try to run the migrations, it has a more informative error message:

```
RAILS_ENV=production rake db:migrate
== 20160927230135 NodeNotNullInMessageDigest: migrating =======================
-- change_column(:message_digests, :node_id, :integer, {:null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Column 'node_id' cannot be NOT NULL: needed in a foreign key constraint 'dpn_server/fk_rails_d4e6ffe21c' SET NULL: ALTER TABLE `message_digests` CHANGE `node_id` `node_id` int(11) NOT NULL
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:531:in `change_column'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/data/src/dlss/dpn/dpn-server/db/migrate/20160927230135_node_not_null_in_message_digest.rb:6:in `up'
```

**Comment by dazza-codes** [comment]
@malakai97 - I cannot find a way to fix the MessageDigest#node_id so that it is `NOT NULL`.  There are some internal rails indexes/FK constraints that are not easily removed.  So, I propose we leave the field alone and do not make any manual changes to `db/schema.rb` to force it.  I propose we back out the migration for making it a null field, because it fails to migrate on a database that contains data and existing FK constraints.

**Comment by dazza-codes** [comment]
Closing this PR and moving the solution to https://github.com/dpn-admin/dpn-server/pull/100

**Comment by darrenleeweber** [comment]
Tried running this migration directly on the SDR dpn-dev box and it seems to have worked.  I don't know why, but it did not work on my laptop using the mysqldump.

**Pull request closed without merging**
